project:
  type: website
lang: fr
website:
  title: "<b>EE·2023</b>"
  favicon: img/cist.png
  twitter-card: true
  site-url: https://cist2023.netlify.app/
  description: "Site web de l'école d'été international 2023 du CIST"
  page-navigation: true
  search: 
    location: navbar
    type: overlay
  navbar:
    background: "#1a8cab"
    left: 
      - href: ecole_thematique.qmd
        text: École d'été
      - href: programme.qmd
        text: Programme
      - href: equipe.qmd
        text: Équipe
      - href: modules.qmd
        text: Modules
      - href: donnees.qmd
        text: Données
    right:
      - href: apropos.qmd
        text: À propos
      - href: contact.qmd
        text: Contacts
    tools:
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/EE-CIST/website
  sidebar:
    contents:
      - href: ecole_thematique.qmd
        text: <b>École d'été</b>
      - programme.qmd
      - href: equipe.qmd
        text: <b>Équipe</b>      
      - href: donnees.qmd
        text: <b>Données</b>
      - modules.qmd
      - href: modules/typ1_enq.qmd
        text: Données d'enquête      
      - href: modules/typ2_rec.qmd
        text: Données recensement    
      - href: modules/typ3_ig.qmd
        text: L'information géographique
      - href: modules/exp1_uni.qmd
        text: Statistique I - univariée
      - href: modules/exp2_biv.qmd
        text: Statistique II - bivariée     
      - href: modules/exp3_mul.qmd
        text: Statistique III - multivariée  
      - href: modules/cart1-2_the.qmd
        text: Cartographie I - thématique         
      - href: modules/cart3_dyn.qmd
        text: Cartographie II - dynamique         
      - href: modules/spa1_sem.qmd
        text: Analayse Spatiale - Semis de points  
      - href: modules/spa2_dis.qmd
        text: Analayse Spatiale II - Distance et accessibilité    
      - href: modules/spa3_int.qmd
        text: Analayse Spatiale III - Interaction spatiale et flux   
      - href: modules/spa4_aut.qmd
        text: Analayse Spatiale IV - Autocorrélation spatiale   
      - href: modules/mod1_quanti.qmd 
        text: Modélisation I
      - href: modules/mod2_quali.qmd 
        text: Modélisation II
      - href: modules/mod3_multiniv.qmd 
        text: Modélisation III
      - href: modules/out2_qgis.qmd
        text: Initiation à QGIS
      - href: modules/out1_r.qmd
        text: Inititation à R 
        

  page-footer: ET CIST·2023 - [![licensebuttons by-sa](https://licensebuttons.net/l/by-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0) - CIST · INED · IRD · LaReSPD · UPC
  margin-header: |
    ![](img/cist.png)


format:
  html:
    theme: 
      light: Minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

