project:
  type: website
lang: fr
website:
  title: "<b>CIST·EE2023</b>"
  favicon: img/cist.png
  twitter-card: true
  site-url: https://cist2023.netlify.app/
  description: "Site web de l'école d'été internationale 2023 du CIST"
  page-navigation: false
  search: 
    location: sidebar
    type: textbox
  navbar:
    background: "#1a8cab"
    left: 
      - href: ecole_thematique.qmd
        text: École d'été
      - href: equipe.qmd
        text: Equipe
      - href: modules.qmd
        text: Modules
    right:
      - href: apropos.qmd
        text: Mentions légales
      - href: conditions.qmd
        text: Conditions d'utilisation
      - href: contact.qmd
        text: Contacts
    tools:
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/EE-CIST/website
  sidebar:
    contents:
      - href: ecole_thematique.qmd
        text: <b>École d'été</b>
      - href: equipe.qmd
        text: <b>Équipe</b>      
      - href: modulesA.qmd
        text: A. COLLECTE DES DONNEES
      - href: modulesB.qmd
        text: B. STATISTIQUE EXPLORATOIRE  
      - href: modulesC.qmd
        text: C. MODELES DE REGRESSION
      - href: modulesD.qmd
        text: D. CARTOGRAPHIE
      - href: modulesE.qmd
        text: E. ANALYSE SPATIALE 
      - href: modulesF.qmd
        text: F. OUTILS      

  page-footer: ET CIST·2023 - [![licensebuttons by-nc-sa](https://licensebuttons.net/l/by-nc-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0) - CIST · INED · IRD · LaReSPD · UPC
  margin-header: |
    ![](img/cist.png)

format:
  html:
    theme: 
      light: Minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

