project:
  type: website
lang: fr
website:
  title: "<b>EE·2023</b>"
  favicon: img/cist.png
  twitter-card: true
  site-url: https://cist2023.netlify.app/
  description: "Site web de l'école d'été international 2023 du CIST"
  page-navigation: true
  search: 
    location: navbar
    type: overlay
  navbar:
    background: "#1a8cab"
    left: 
      - href: ecole_thematique.qmd
        text: École d'été
      - href: programme.qmd
        text: Programme
      - href: equipe.qmd
        text: Équipe
      - href: modules.qmd
        text: Modules
      - href: donnees.qmd
        text: Données
    right:
      - href: apropos.qmd
        text: À propos
      - href: contact.qmd
        text: Contact
    tools:
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/EE-CIST/website
  sidebar:
    contents:
      - href: ecole_thematique.qmd
        text: <b>École d'été</b>
      - programme.qmd
      - href: equipe.qmd
        text: <b>Équipe</b>      
      - href: donnees.qmd
        text: <b>Données</b>
      - modules.qmd
      - href: modules/A_data_type.qmd
        text: L'info. géographique
      - href: modules/B_data_type.qmd
        text: Données d'enquête      
      - href: modules/C_data_type.qmd
        text: Données recensement    
      - href: modules/F_stat_uni.qmd
        text: Statistique univariée
      - href: modules/H_stat_biv.qmd
        text: Statistique bivariée     
      - href: modules/K_stat_multi.qmd
        text: Statistique multivariée  
      - href: modules/G_cartographie.qmd
        text: Cartographie          
      - href: modules/I_semi_point.qmd
        text: Semis de points  
      - href: modules/J_distance_acces.qmd
        text: Accessibilité    
      - href: modules/L_Modelisation.qmd 
        text: Modélisation
      - href: modules/D_QGIS.qmd
        text: Initiation à QGIS
      - href: modules/E_R.qmd
        text: Inititation à R 
        

  page-footer: ET CIST·2023 - [![licensebuttons by-sa](https://licensebuttons.net/l/by-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0) - INED · IRD · LaReSPD
  margin-header: |
    ![](img/cist.png)


format:
  html:
    theme: 
      light: Minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

