---
title: "École d'été internationale du CIST"
about:
  template: marquee
  image : img/header.png
  image-width: 40em
  image-shape: rounded
---

## Méthodes et outils des sciences des territoires : une perspective Nord-Sud

> Première action de formation d’envergure du CIST coordonnée par Mouftaou Amadou Sanni (LARESPD / Université de Parakou, Bénin), Emmanuel Bonnet (IRD), Claude Grasland (CIST) et France Guérin-Pace (Ined)


Cette école d’été internationale est destinée à mettre en commun des ressources pédagogiques et scientifiques d’une trentaine de formateur.rices du Nord et du Sud, puis de diffuser ces connaissances auprès d’un nombre équivalent de doctorant.es et ingénieur.es. Menée dans une perspective pluridisciplinaire, l’école permet de diffuser les concepts et méthodes les plus avancés des sciences territoriales, en privilégiant l’emploi d’outils informatiques d’accès libre.

### Une école en 2 étapes
#### Première étape de l’école d’été sur le campus Condorcet (juin 2022)

La première étape de ce projet se tiendra sur le campus Condorcet avec l’accueil durant une semaine d’une quinzaine de formateur·rices de pays d’Afrique francophone subsaharienne (Burkina Faso, Bénin, Cameroun, Côte d’Ivoire, Mali, Niger, Sénégal, Togo).
Avec une quinzaine d’homologues du Nord, ils échangeront afin de mettre en place très concrètement un corpus d’enseignements, d’outils et de données qui pourront être mobilisés en fonction des besoins scientifiques et pédagogiques des participant.es autour de thématiques ciblées.

*Initialement prévue en janvier 2022, cette première phase a été reportée en juin 2022 en raison du contexte sanitaire.*

### Seconde étape de l’école d’été au Bénin (début 2023)

La deuxième étape se déroulera début 2023 au siège de l’Institut régional de santé Comal Alfred Quesnum (IRSP-CAQ) à Ouidah (Bénin). L’école d’été réunira à nouveau dureant une semaine l’ensemble des formateur·rices présent·es au cours de la première semaine, ainsi qu’un ensemble d’apprenant.es (doctorant.es, ingénieur.es, etc.).
Les modalités de sélection des apprenant.es seront décidées lors de la première étape en privilégiant autant que possible la diversité géographique et disciplinaire.

Cette seconde étape permettra de tester, améliorer et valider les modules pédagogiques mis au point au cours de la première phase qui seront, ensuite, largement diffusés.