---
title: "The Demographic and Health Surveys (DHS)"
name: "EDS/DHS Afrique"
nocite: '@*'
csl: geo.csl
categories: 
- Type de données I
- Statistiques I 
- Statistiques III
about:
  template: marquee
producteur: DHS
nature: enquete
title-block-categories: true
format:
  html: 
    css: styles_bis.css
---

**Nom** : The Demographic and Health Surveys (DHS) *(Enquête Démographie et Santé)*

**Mots-clés** : afrique - santé - démographie - alimentation

**Nature** : Données d'enquêtes

**Description** : Enquêtes produisant des données sur la santé (notamment sida), la population et l'alimentation des pays en développement.

**Producteur & Fournisseur/URL d'accès** : [The Demographic and Health Surveys (DHS) Program](https://www.dhsprogram.com/)

**Date** : Dates variables selon les pays (Togo:2013),( Bénin:2017), (Burkina Faso: 2010), (Mali: 2018)

**Etendue spatiale** : Pays africains ayant participé aux enquêtes(nb?)

**Echelle** : Individus

**Nombre d'observations** : Variable selon la base utilisée (Ménage: 115 310), (Femmes: non calculé), (Hommes:16 689)

**Nombre de variables** : 14

**Description des variables** :

| Nom | Description | Sources | Type |
|-----|-------------|---------|------|
|     |             |         |      |
|     |             |         |      |

**Méthodologie** :

**Transformation** : population des villes obtenues en combinant les données de recensement et l'imagerie satellitaire

**Commentaire** :

------------------------------------------------------------------------

**Licence** : [Se reporter aux consignes disponibles sur le site DHS :](https://dhsprogram.com/publications/Recommended)

-   **Module(s) de formation concerné(s)**:

    -   [**Type de données I** - Enquêtes](../modules/typ1_enq.qmd)

    -   [**Statistiques I** - Univariées](../modules/exp1_uni.qmd)

    -   [**Statistiques III** - Multivariées](../modules/exp3_mul.qmd)

<center><a href="" class="btn btn-info" role="button" aria-disabled="true"><i class="bi bi-cloud-arrow-down"></i> Data.zip</a></center>
