---
title: "Enquête sur les transformations de la société tunisienne"
name: "Enquête Tunisie"
nocite: '@*'
csl: geo.csl
categories: 
  - Type de données I
  - Statistiques III
about:
  template: marquee
producteur:
  - INED
  - CERP
nature: enquete
title-block-categories: true
format:
  html: 
    css: styles_bis.css
---

**Nom** : Enquête sur les transformations de la société tunisienne

**Mots-clés** : grille biographique - migrations - emploi - langue

**Nature** : Données d'enquête socio démographique avec une grille biographique

**Description** :

**Producteur** : INED-CERP

**Fournisseur/URL d'accès** : non publiées

**Date** : 2016

**Etendue spatiale** : Tunisie

**Echelle** : échantillon de districts représentatifs de la population tunisienne à l'échelle des gouvernorats

**Nombre d'observations** : 3463 personnes

**Nombre de variables** : 1047

**Description des variables** :

    | Nom | Description | Sources | Type |
    |-----|-------------|---------|------|
    |     |             |         |      |
    |     |             |         |      |

**Méthodologie** :

**Transformation** : Données ayant subit une transformation/modification ? OUI/NON

**Commentaire** :

------------------------------------------------------------------------

**Licence** :

-   **Module(s) de formation concerné(s)** :

    -   [**Type de données I** - Enquêtes](../modules/A_data_type.qmd)

    -   [**Statistiques III** - Multivariées](../modules/K_stat_multi.qmd)
    
<center><a href="" class="btn btn-info" role="button" aria-disabled="true"><i class="bi bi-cloud-arrow-down"></i> Data.zip</a></center>
