---
title: "Africapolis"
name: "Africapolis"
nocite: '@*'
csl: geo.csl
categories: 
- agglomération
- afrique
- urbanisation
- géographie
- démographie
about:
  template: marquee
  # links:
    # - icon: github
    #   text: Producteur des donées
    #   href: https://github.com
module: 
- Type de données II
- Analyse Spatiale I
- Analyse Spatiale III
- Outils - QGIS
nature: statistiques
title-block-categories: true

format:
  html: 
    css: styles_bis.css
---

-   **Nom** : AFRICAPOLIS

-   **Nature** : Données statistiques et fonds de carte SIG

-   **Description** : Base de donnée sur les agglomérations morphologiques de plus de 10 000 habitants de 54 pays africains

-   **Producteur** : OECD/SWAC (2020), Africapolis (database), www.africapolis.org (accessed 2022-11-17).

-   **Fournisseur/URL d'accès** : [africapolis](https://africapolis.org/fr)

-   **Date** : 1950- 1960 - 1970 - 1980 - 1990 - 2000 - 2010 - 2015

-   **Etendue spatiale** : Ensemble de l'Afrique (54 pays)

-   **Echelle** : Infra-national, Agglomération de + de 10 000 habitants selon le critère de continuité du bâti

-   **Nombre d'observations** : 9180

-   **Nombre de variables** : 18

-   **Description des variables** :

    | Nom | Description | Sources | Type |
    |-----|-------------|---------|------|
    |     |             |         |      |
    |     |             |         |      |

-   **Méthodologie** :

-   **Transformation** : population des villes obtenues en combinant les données de recensement et l'imagerie satellitaire

-   **Commentaire** :

------------------------------------------------------------------------

-   Licence:

-   Citation:

-   Lien de téléchargement : A remplir une fois que les données seront sur le site de l'école

-   Module(s) de formation concerné(s):

    -   [**Type de données II** - Recensement](../modules/B_data_type.qmd)
    -   [**Analyse Spatiale I** : Semis de points](../modules/I_semi_point.qmd)
    -   [**Analyse Spatiale III** : Distance et accessibilité](../modules/J_distance_acces.qmd)
    -   [**Outils 2** : QGIS](../modules/D_QGIS.qmd)

-   TAGS: mots-clé
