name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":"${{github.workspace}}"
     steps:
       - name: info
         run: (ls -la /)

       - name: copy
         run: cp -R /root/project ${{github.workspace}}/

       - name: check quarto
         run: (quarto check)
         working-directory: /root/project

       - name: check renvlock
         run: (cat renv.lock)
         working-directory: /root/project
