name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":"${{github.workspace}}"
     steps:

       - name: copy
         run: cp -R /project/* ${{github.workspace}}/

       - name: print sessioninfo
         run: (Rscript -e "print (sessionInfo())")

       - name: check renvlock
         run: (cat renv.lock)
         working-directory: /project
