name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":"${{github.workspace}}"
     steps:

       - name: copy
         run: (mkdir -p ${{github.workspace}}/project &&  cp -R /project/* ${{github.workspace}}/project)

       - name: print project files
         run: (ls -la)
         working-directory: /project
         
       - name: print project files 2
         run: (ls -la ${{github.workspace}})
         
       - name: quarto check
         run: (quarto check)
         working-directory: /project
         
       - name: print sessioninfo
         run: (Rscript -e "print (sessionInfo())")
         working-directory: /project

       - name: quarto render
         run: (quarto render ..)
         working-directory: /project
