name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":"${{github.workspace}}"
     steps:

       - name: copy
         run: cp -R /project/* ${{github.workspace}}/

       - name: check quarto
         run: (quarto check)

       - name: check renvlock
         run: (cat renv.lock)
         working-directory: /project
