name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":"${{github.workspace}}"
     steps:

       - name: copy
         run: (mkdir -p ${{github.workspace}}/project &&  cp -R /project/* ${{github.workspace}}/project)

       - name: print project filess
         run: (ls -la)
         working-directory: /project


       - name: print sessioninfo
         run: (Rscript -e "print (sessionInfo())")
         working-directory: /project

       - name: check renvlock
         run: (cat renv.lock)
         working-directory: /project
