name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     container:
        image: sreycoyrehourcq/cist-ee:main
     steps:
       - name: info
         run: (pwd)

       - name: check quarto
         run: (quarto check)
         working-directory: /root/project

       - name: check renvlock
         run: (cat renv.lock)
         working-directory: /root/project
