name : build-site

on:
  push:
    branches: [ main ]

jobs:
  container-quarto:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3

     container:
        image: sreycoyrehourcq/cist-ee:main
        options:
          --user root
          -v "${{github.workspace}}":/project/website
     steps:

       - name: print project volume files
         run: (ls -la)
         working-directory: /project/website

       - name: quarto check
         run: (quarto check)
         working-directory: /project

       - name: print sessioninfo
         run: (Rscript -e "print (sessionInfo())")
         working-directory: /project

       - name: quarto render
         run: (quarto render ./website)
         working-directory: /project
